module.exports.GROCERY_CATEGORIES = [
  "Biscuits & Cakes",
  "Cereals & Breakfast",
  "Chips & Namkeens",
  "Chocolates",
  "Dairy",
  "Drinks",
  "Dry Fruits & Nuts",
  "Fruits",
  "Ice Cream",
  "Instant Food",
  "Meat",
  "Oils & Ghee",
  "Seafood",
  "Vegetables",
];
