module.exports.GROCERY_CATEGORIES = [
  "Fruits",
  "Vegetables",
  "Dairy",
  "Bakery",
  "Beverages",
  "Snacks",
  "Meat",
  "Seafood",
  "Frozen Foods",
  "Grains & Cereals",
  "Pulses & Lentils",
  "Spices & Condiments",
  "Oils & Ghee",
  "Dry Fruits & Nuts",
  "Cleaning Supplies",
  "Personal Care",
  "Baby Care",
  "Packaged Foods",
  "Stationery & Household",
];
